"""
Customer Churn Prediction — ChurnGuard AI (Premium UI)
======================================================
Dark glassmorphism interface with animated background, theme toggle,
flip-in result cards and an insights dashboard.

Tabs:
  1. Predict Churn   -> calls FastAPI /predict endpoint
  2. Model Insights  -> metrics, confusion matrix, feature importance, plots
"""

import os
import functools
import re as _regex
from datetime import date
from pathlib import Path

import requests
import json
import plotly.express as px
import plotly.graph_objects as go
import gradio as gr

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
API_URL = os.getenv("API_URL", "http://localhost:8000")
PREDICT_ENDPOINT = f"{API_URL}/predict"

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_PATH = BASE_DIR / "data" / "customer_churn_v2.0_clean.csv"
MODEL_PATH = BASE_DIR / "models" / "customer_churn_model.joblib"

# Precomputed dashboard payload (generated by scripts/export_insights.py).
# Lets the Insights tab render instantly on cold serverless/free tiers.
INSIGHTS_JSON = Path(__file__).resolve().parent / "insights.json"

# --------------------------------------------------------------------------- #
# Custom CSS — dark glassmorphism design system
# --------------------------------------------------------------------------- #
CUSTOM_CSS = """
.gradio-container {max-width: 1180px !important; margin: auto !important;}

/* ================= ANIMATED BACKGROUND ORBS ================= */
.gradio-container {position: relative;}
.gradio-container::before,
.gradio-container::after {
    content: ""; position: fixed; border-radius: 50%;
    filter: blur(115px); z-index: -1; pointer-events: none;
    opacity: .38;
}
.gradio-container::before {
    width: 540px; height: 540px; top: -170px; left: -130px;
    background: #a21caf;
    animation: drift1 17s ease-in-out infinite alternate;
}
.gradio-container::after {
    width: 560px; height: 560px; bottom: -200px; right: -150px;
    background: #c026d3;
    animation: drift2 21s ease-in-out infinite alternate;
}
@keyframes drift1 {to {transform: translate(150px, 130px) scale(1.18);}}
@keyframes drift2 {to {transform: translate(-160px, -110px) scale(1.12);}}
.gradio-container:not(.dark)::before,
.gradio-container:not(.dark)::after {opacity: .17;}

/* ================= GLASS CARDS =================
   Component surfaces (blocks, inputs, radios, numbers) are themed through
   THEME.set(*_dark tokens) below — NOT via hard CSS overrides, so every
   control stays fully visible and correctly colored. */
.block {border-radius: 18px !important;}

/* ================= HERO BANNER ================= */
.hero {
    position: relative; overflow: hidden;
    background: linear-gradient(135deg, #7e22ce 0%, #a21caf 45%, #c026d3 75%, #e879f9 100%);
    background-size: 220% 220%;
    animation: heroShift 9s ease infinite;
    border-radius: 24px;
    padding: 40px 30px 36px;
    text-align: center; color: #fff;
    box-shadow: 0 18px 50px rgba(124, 58, 237, .45);
    margin-bottom: 12px;
}
@keyframes heroShift {
    0%, 100% {background-position: 0% 50%;}
    50%      {background-position: 100% 50%;}
}
.hero h1 {margin: 0; font-size: 2.5em; font-weight: 800; letter-spacing: -.5px;
          text-shadow: 0 3px 18px rgba(0, 0, 0, .25);}
.hero p  {margin: 10px auto 0; font-size: 1.06em; opacity: .95; max-width: 620px;}
.hero .badge {
    display: inline-block; margin-top: 16px; padding: 6px 18px;
    background: rgba(255, 255, 255, .16); border: 1px solid rgba(255, 255, 255, .38);
    border-radius: 999px; font-size: .8em; letter-spacing: 1.2px;
    backdrop-filter: blur(6px);
}
.hero::before, .hero::after {
    content: ""; position: absolute; border-radius: 50%;
    background: rgba(255, 255, 255, .14); filter: blur(6px);
}
.hero::before {width: 190px; height: 190px; top: -80px; left: -60px;
               animation: floatOrb 7s ease-in-out infinite alternate;}
.hero::after  {width: 150px; height: 150px; bottom: -70px; right: -40px;
               animation: floatOrb 9s ease-in-out infinite alternate-reverse;}
@keyframes floatOrb {to {transform: translate(34px, 26px) scale(1.15);}}

/* ================= THEME TOGGLE ================= */
.theme-row {display: flex; justify-content: flex-end; gap: 8px; margin-top: -52px;
            padding: 0 6px 8px; position: relative; z-index: 5;}
.theme-btn {
    background: rgba(255, 255, 255, .14) !important;
    border: 1px solid rgba(255, 255, 255, .35) !important;
    color: #fff !important; border-radius: 999px !important;
    padding: 6px 14px !important; font-size: .85rem !important;
    backdrop-filter: blur(8px);
    transition: transform .2s ease, background .2s ease !important;
}
.theme-btn:hover {transform: scale(1.06) rotate(-6deg) !important;
                  background: rgba(255, 255, 255, .26) !important;}

/* ================= RESULT CARD ================= */
.result-card {
    border-radius: 20px; padding: 30px; text-align: center;
    transform-origin: center top;
    animation: flipIn .65s cubic-bezier(.2, .85, .3, 1.05) both;
}
@keyframes flipIn {
    0%   {opacity: 0; transform: perspective(900px) rotateX(-30deg)
                       translateY(26px);}
    100% {opacity: 1; transform: perspective(900px) rotateX(0) translateY(0);}
}
.result-safe {
    background: linear-gradient(135deg, rgba(16, 185, 129, .17),
                                rgba(16, 185, 129, .06));
    border: 1.5px solid rgba(16, 185, 129, .55);
    box-shadow: 0 14px 38px rgba(16, 185, 129, .22);
}
.result-risk {
    background: linear-gradient(135deg, rgba(239, 68, 68, .17),
                                rgba(249, 115, 22, .07));
    border: 1.5px solid rgba(239, 68, 68, .55);
    box-shadow: 0 14px 38px rgba(239, 68, 68, .22);
}
.result-emoji {font-size: 3.1em; display: inline-block;
               animation: bounceIn .8s cubic-bezier(.2, 1.4, .4, 1) both .25s;}
@keyframes bounceIn {0% {transform: scale(0);} 70% {transform: scale(1.25);}
                     100% {transform: scale(1);}}
.result-title {font-size: 1.6em; font-weight: 800; margin-top: 8px;
               display: flex; align-items: center; justify-content: center;
               gap: 10px;}
.result-sub {font-size: .96em; color: #94a3b8; margin-top: 6px;}

.pulse-dot {width: 11px; height: 11px; border-radius: 50%;
            display: inline-block; animation: pulseDot 1.7s ease-out infinite;}
.pulse-dot.safe {background: #10b981;}
.pulse-dot.risk {background: #ef4444;}
@keyframes pulseDot {
    0%   {box-shadow: 0 0 0 0 rgba(16, 185, 129, .65);}
    70%  {box-shadow: 0 0 0 13px rgba(16, 185, 129, 0);}
    100% {box-shadow: 0 0 0 0 rgba(16, 185, 129, 0);}
}
.pulse-dot.risk {animation-name: pulseDotRisk;}
@keyframes pulseDotRisk {
    0%   {box-shadow: 0 0 0 0 rgba(239, 68, 68, .65);}
    70%  {box-shadow: 0 0 0 13px rgba(239, 68, 68, 0);}
    100% {box-shadow: 0 0 0 0 rgba(239, 68, 68, 0);}
}

/* ================= CONFIDENCE BAR ================= */
.conf-wrap {
    margin-top: 22px; height: 22px; border-radius: 999px;
    background: rgba(148, 163, 184, .22); overflow: hidden;
    box-shadow: inset 0 1px 4px rgba(0, 0, 0, .25);
}
.conf-fill {
    position: relative; height: 100%; border-radius: 999px; overflow: hidden;
    background: linear-gradient(90deg, #34d399, #10b981);
    animation: grow 1s cubic-bezier(.25, .8, .35, 1) both;
}
.conf-fill.risk {background: linear-gradient(90deg, #fb923c, #ef4444);}
@keyframes grow {from {width: 0 !important;}}
.conf-fill::after {
    content: ""; position: absolute; inset: 0; transform: translateX(-100%);
    background: linear-gradient(90deg, transparent, rgba(255, 255, 255, .5),
                                transparent);
    animation: shine 2.4s linear infinite;
}
@keyframes shine {to {transform: translateX(100%);}}
.conf-label {font-weight: 700; margin-top: 9px; color: #cbd5e1;
             letter-spacing: .3px;}

/* ================= DASHBOARD METRIC CARDS ================= */
.metric-row {display: flex; gap: 14px; flex-wrap: wrap;
             justify-content: center; margin-bottom: 6px;}
.metric-card {
    flex: 1; min-width: 150px; cursor: default;
    background: linear-gradient(160deg, rgba(192, 38, 211, .15), rgba(255, 255, 255, .03));
    border: 1px solid rgba(232, 121, 249, .38);
    border-radius: 18px; padding: 20px 12px; text-align: center;
    backdrop-filter: blur(10px);
    transition: transform .25s ease, box-shadow .25s ease;
}
.metric-card:hover {transform: translateY(-5px);
                    box-shadow: 0 14px 32px rgba(192, 38, 211, .4);}
.metric-value {
    font-size: 2em; font-weight: 800;
    background: linear-gradient(90deg, #f0abfc, #d8b4fe);
    -webkit-background-clip: text; background-clip: text;
    -webkit-text-fill-color: transparent;
}
.gradio-container:not(.dark) .metric-value {-webkit-text-fill-color: #a21caf;}
.metric-name {font-size: .82em; text-transform: uppercase; letter-spacing: 1.4px;
              color: #94a3b8; margin-top: 4px;}

/* ================= TAB PILLS ================= */
.tab-nav button {border-radius: 999px !important; padding: 9px 20px !important;
                 font-weight: 600 !important; transition: all .2s ease !important;}
.tab-nav button.selected {
    background: linear-gradient(135deg, #c026d3, #9333ea) !important;
    color: #fff !important;
    box-shadow: 0 8px 22px rgba(124, 58, 237, .42) !important;
}

/* ================= PREDICT BUTTON ================= */
button.primary {transition: transform .2s ease, filter .2s ease !important;}
button.primary:hover {transform: translateY(-2px) scale(1.012);
                      filter: brightness(1.1);}

/* ================= SCROLLBAR ================= */
::-webkit-scrollbar {width: 10px; height: 10px;}
::-webkit-scrollbar-track {background: transparent;}
::-webkit-scrollbar-thumb {
    background: linear-gradient(#c026d3, #9333ea); border-radius: 999px;
    border: 2px solid transparent; background-clip: padding-box;
}

/* ================= FOOTER ================= */
.footer {text-align: center; color: #8b93a7; font-size: .88em;
         padding: 28px 0 8px;}
.footer a {color: #a78bfa; text-decoration: none;}
"""

# --------------------------------------------------------------------------- #
# Client-side JS helpers (theme handling)
# --------------------------------------------------------------------------- #
FORCE_DARK_JS = """
() => {
    const url = new URL(window.location);
    if (!url.searchParams.get('__theme')) {
        url.searchParams.set('__theme', 'dark');
        window.location.href = url.href;
    }
}
"""

TOGGLE_THEME_JS = """
() => {
    const url = new URL(window.location);
    const current = url.searchParams.get('__theme') || 'dark';
    url.searchParams.set('__theme', current === 'dark' ? 'light' : 'dark');
    window.location.href = url.href;
}
"""

# --------------------------------------------------------------------------- #
# Prediction (calls FastAPI)
# --------------------------------------------------------------------------- #
def build_payload(age, gender, location, email, tenure_months, monthly_charges,
                  total_charges, contract_type, internet_service, phone_service,
                  online_security, tech_support, payment_method,
                  satisfaction_score, support_tickets, last_contact_date):
    return {
        "age": int(age),
        "gender": gender.lower(),
        "location": location.lower(),
        "email": str(email).strip(),
        "tenure_months": float(tenure_months),
        "monthly_charges": float(monthly_charges),
        "total_charges": float(total_charges),
        "contract_type": contract_type.lower(),
        "internet_service": internet_service.lower(),
        "phone_service": phone_service.lower(),
        "online_security": online_security.lower(),
        "tech_support": tech_support.lower(),
        "payment_method": payment_method.lower(),
        "satisfaction_score": float(satisfaction_score),
        "support_tickets": int(support_tickets),
        "last_contact_date": last_contact_date.isoformat()
        if isinstance(last_contact_date, date) else str(last_contact_date),
    }


def render_result(label, confidence):
    churn_prob = confidence if label == "yes" else round(1 - confidence, 4)

    if label == "yes":
        card_cls, emoji, dot_cls = "result-risk", "⚠️", "risk"
        title = "High Churn Risk"
        sub = "This customer is likely to LEAVE — retention action recommended."
        fill_cls = "conf-fill risk"
    else:
        card_cls, emoji, dot_cls = "result-safe", "✅", "safe"
        title = "Customer Likely to Stay"
        sub = "Low churn probability — customer looks satisfied and loyal."
        fill_cls = "conf-fill"

    pct = int(round(churn_prob * 100))
    return f"""
    <div class="result-card {card_cls}">
        <div class="result-emoji">{emoji}</div>
        <div class="result-title">
            <span class="pulse-dot {dot_cls}"></span>{title}
        </div>
        <div class="result-sub">{sub}</div>
        <div class="conf-wrap">
            <div class="{fill_cls}" style="width: {pct}%"></div>
        </div>
        <div class="conf-label">Churn probability&nbsp;·&nbsp;{churn_prob*100:.1f}%</div>
    </div>
    """


def predict_churn(age, gender, location, email, tenure_months, monthly_charges,
                  total_charges, contract_type, internet_service, phone_service,
                  online_security, tech_support, payment_method,
                  satisfaction_score, support_tickets, last_contact_date):
    payload = build_payload(age, gender, location, email, tenure_months,
                            monthly_charges, total_charges, contract_type,
                            internet_service, phone_service, online_security,
                            tech_support, payment_method, satisfaction_score,
                            support_tickets, last_contact_date)
    try:
        resp = requests.post(PREDICT_ENDPOINT, json=payload, timeout=30)
    except requests.exceptions.ConnectionError:
        return ("🔴 **Cannot reach the prediction API.**\n\n"
                "Start it first:\n```\nuvicorn app:app --reload\n```")
    except requests.exceptions.Timeout:
        return "⏱️ **The API took too long to respond.** Please try again."

    if resp.status_code != 200:
        detail = resp.json().get("detail", resp.text) if resp.headers.get(
            "content-type", "").startswith("application/json") else resp.text
        return f"❌ **API error ({resp.status_code}):**\n\n{detail}"

    data = resp.json()
    return render_result(data["label"], float(data["confidence"]))

# --------------------------------------------------------------------------- #
# Dashboard — model insights
# --------------------------------------------------------------------------- #
def _histogram_payload(values):
    import numpy as np
    counts, edges = np.histogram(values, bins=40)
    mids = ((edges[:-1] + edges[1:]) / 2).round(3)
    return {"mids": mids.tolist(), "counts": counts.tolist()}


@functools.lru_cache(maxsize=1)
def get_insights():
    """Return the Insights-dashboard payload as a plain dict.

    Fast path : ui/insights.json, precomputed by scripts/export_insights.py
                -> renders instantly even on cold free-tier containers.
    Fallback  : full computation (pandas/sklearn/joblib); result is written
                back to ui/insights.json so subsequent loads stay fast.
    """
    if INSIGHTS_JSON.exists():
        return json.loads(INSIGHTS_JSON.read_text(encoding="utf-8"))
    payload = _compute_insights()
    try:
        INSIGHTS_JSON.write_text(json.dumps(payload), encoding="utf-8")
    except OSError:
        pass
    return payload


def _compute_insights():
    import joblib
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                                 f1_score, confusion_matrix)

    df = pd.read_csv(DATA_PATH)
    model = joblib.load(MODEL_PATH)

    x = df.drop("churn", axis=1)
    y = df["churn"]

    _, x_test, _, y_test = train_test_split(x, y, test_size=0.2,
                                            random_state=42, shuffle=True)
    y_pred = model.predict(x_test)

    metrics = {
        "Accuracy":  accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, pos_label="yes"),
        "Recall":    recall_score(y_test, y_pred, pos_label="yes"),
        "F1 Score":  f1_score(y_test, y_pred, pos_label="yes"),
    }
    cm = confusion_matrix(y_test, y_pred, labels=["no", "yes"])

    # ---- feature importance from XGBoost estimators inside BaggingClassifier
    try:
        pre = model.named_steps["processors"]
        bag = model.named_steps["model"]
        all_cols = [str(c) for c in x.columns]

        def safe_out(trans):
            """Fit-time feature names, tolerating mid-pipeline
            FunctionTransformers that break sklearn's naming chain."""
            candidates = []
            if hasattr(trans, "steps"):
                candidates.extend(step for _, step in reversed(trans.steps))
            for step in candidates:
                try:
                    return step.get_feature_names_out()
                except Exception:
                    continue
            raise ValueError("no step provides feature names")

        def transformer_names(ct):
            names = []
            for name, trans, cols in ct.transformers_:
                if trans == "drop":
                    continue
                col_list = [str(c) for c in (cols if isinstance(cols, (
                    list, tuple, pd.Index)) else [cols])]
                if name == "remainder":          # may be positional indices
                    names.extend(
                        all_cols[int(c)] if str(c).isdigit() else c
                        for c in col_list)
                    continue
                try:
                    out = [str(n).split("__")[-1] for n in safe_out(trans)]
                    # pipelines fitted without DataFrame column names emit
                    # generic x0, x1_cat labels — decode via first step's
                    # own fit-time feature list.
                    first = (trans.steps[0][1]
                             if hasattr(trans, "steps") else trans)
                    try:
                        fit_inputs = [str(n).split("__")[-1] for n in
                                      first.get_feature_names_out()]
                    except Exception:
                        fit_inputs = []
                    pretty = []
                    for n in out:
                        m = _regex.match(r"^x(\d+)(?:_(.*))?$", n)
                        if m and fit_inputs and int(m.group(1)) < len(
                                fit_inputs):
                            base = fit_inputs[int(m.group(1))]
                            cat = m.group(2)
                            pretty.append(f"{base}_{cat}" if cat else base)
                        else:
                            pretty.append(n)
                    names.extend(pretty)
                except Exception:
                    names.extend(col_list)
            return names

        def humanize(n):
            n = n.strip().replace("_", " ")
            if n.endswith((" True", " False")):
                n = n.rsplit(" ", 1)[0]
            if "missingindicator" in n.lower():
                n = (n.replace("missingindicator", "").strip()
                      + " (was missing)")
            return n

        feat_names = [humanize(n) for n in transformer_names(pre)]
        imps = np.mean([est.feature_importances_ for est in bag.estimators_],
                       axis=0)
        if len(feat_names) != len(imps):
            raise ValueError("feature name/importance length mismatch")

        imp_df = (pd.DataFrame({"feature": feat_names, "importance": imps})
                    .groupby("feature", as_index=False).sum()
                    .sort_values("importance", ascending=False).head(12))
        imp_df["importance"] /= imp_df["importance"].sum()
        imp_df = imp_df.iloc[::-1]
    except Exception:
        imp_df = pd.DataFrame({"feature": [], "importance": []})

    return {
        "metrics": {k: round(float(v), 4) for k, v in metrics.items()},
        "confusion_matrix": cm.astype(int).tolist(),
        "feature_importance": imp_df.to_dict(orient="records"),
        "churn_counts": [
            {"label": "Retained",
             "count": int((df["churn"] == "no").sum())},
            {"label": "Churned",
             "count": int((df["churn"] == "yes").sum())},
        ],
        "histograms": {
            "age": _histogram_payload(df["age"].dropna().to_numpy()),
            "monthly_charges": _histogram_payload(
                df["monthly_charges"].dropna().to_numpy()),
            "tenure_months": _histogram_payload(
                df["tenure_months"].dropna().to_numpy()),
        },
        "meta": {"rows": int(len(df))},
    }


def metric_cards_html(metrics):
    cards = "".join(
        f'<div class="metric-card"><div class="metric-value">{v*100:.1f}%</div>'
        f'<div class="metric-name">{k}</div></div>'
        for k, v in metrics.items())
    return f'<div class="metric-row">{cards}</div>'


def _style(fig, height=330):
    """Transparent dark-glass Plotly styling."""
    fig.update_layout(
        template="plotly_dark",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#cbd5e1", family="Inter, sans-serif"),
        title_font=dict(size=16, color="#e2e8f0"),
        margin=dict(t=54, b=18, l=18, r=18),
        height=height,
    )
    fig.update_xaxes(gridcolor="rgba(148,163,184,.15)", zeroline=False)
    fig.update_yaxes(gridcolor="rgba(148,163,184,.15)", zeroline=False)
    return fig


def donut_chart(churn_counts):
    colors = {"Churned": "#ef4444", "Retained": "#10b981"}
    fig = px.pie(churn_counts, names="label", values="count", hole=0.62,
                 color="label", color_discrete_map=colors,
                 title="Customer Churn Split")
    fig.update_traces(textinfo="percent+label",
                      textfont=dict(color="#e2e8f0"),
                      pull=[0.04, 0],
                      marker=dict(line=dict(color="rgba(0,0,0,0)", width=0)))
    return _style(fig)


def confusion_heatmap(cm):
    fig = go.Figure(go.Heatmap(
        z=cm, x=["Pred: No", "Pred: Yes"], y=["Actual: No", "Actual: Yes"],
        colorscale=[[0, "rgba(147,51,234,.15)"], [1, "#9333ea"]],
        showscale=False, xgap=4, ygap=4,
        text=cm, texttemplate="%{text}",
        textfont=dict(size=22, color="#ffffff")))
    fig.update_layout(title="Confusion Matrix",
                      yaxis=dict(autorange="reversed"))
    return _style(fig)


def importance_bar(imp_records):
    if not imp_records:
        fig = go.Figure()
        fig.update_layout(title="Feature Importance (unavailable)")
        return _style(fig, height=430)
    fig = go.Figure(go.Bar(
        x=[r["importance"] for r in imp_records],
        y=[r["feature"] for r in imp_records],
        orientation="h",
        marker=dict(color=[r["importance"] for r in imp_records],
                    colorscale="Purp", cornerradius=4)))
    fig.update_layout(title="Top Feature Importances")
    fig.update_yaxes(title=None)
    fig.update_xaxes(title=None)
    return _style(fig, height=430)


def distribution_fig(hist, title, color="#e879f9"):
    fig = go.Figure(go.Bar(
        x=hist["mids"], y=hist["counts"],
        marker_color=color, marker=dict(cornerradius=3),
        opacity=.9))
    fig.update_layout(title=title, bargap=0.04)
    return _style(fig, height=300)


def load_dashboard():
    payload = get_insights()
    hists = payload["histograms"]
    return (
        metric_cards_html(payload["metrics"]),
        donut_chart(payload["churn_counts"]),
        confusion_heatmap(payload["confusion_matrix"]),
        importance_bar(payload["feature_importance"]),
        distribution_fig(hists["age"], "Age Distribution"),
        distribution_fig(hists["monthly_charges"],
                         "Monthly Charges Distribution", "#fb923c"),
        distribution_fig(hists["tenure_months"], "Tenure Distribution",
                         "#34d399"),
    )

# --------------------------------------------------------------------------- #
# UI Layout
# --------------------------------------------------------------------------- #
CITIES = ["mumbai", "delhi", "bangalore", "chennai", "kolkata",
          "hyderabad", "pune"]
PAYMENTS = ["electronic check", "credit card (automatic)", "mailed check",
            "bank transfer (automatic)", "upi", "cash"]

HERO_HTML = """
<div class="hero">
    <h1>🔮 ChurnGuard AI</h1>
    <p>Know who's leaving before they do — powered by an XGBoost ensemble,
       served through FastAPI &amp; wrapped in a beautiful interface.</p>
    <span class="badge">FASTAPI · GRADIO · DOCKER</span>
</div>
"""

FOOTER_HTML = """
<div class="footer">
    Built with ❤️ using FastAPI + Gradio · Model: Bagging XGBoost Ensemble<br>
    ⭐ Star this project on GitHub!
</div>
"""


def build_ui():
    with gr.Blocks(title="ChurnGuard AI") as demo:

        gr.HTML(HERO_HTML)

        with gr.Row(elem_classes=["theme-row"]):
            theme_btn = gr.Button("🌓 Toggle Theme", elem_classes=["theme-btn"],
                                  size="sm")

        with gr.Tabs():

            # ---------------- TAB 1 : PREDICTION ---------------- #
            with gr.Tab("🔮 Predict Churn"):
                gr.Markdown("### Enter customer details below and hit "
                            "**Predict** to see churn risk instantly.")

                with gr.Row():
                    # -------- left column -------- #
                    with gr.Column():
                        with gr.Accordion("👤 Personal Info", open=True):
                            age = gr.Number(label="Age", value=32,
                                            precision=0, minimum=18, maximum=99)
                            gender = gr.Radio(["male", "female", "other"],
                                              label="Gender", value="female")
                            location = gr.Dropdown(CITIES, label="Location",
                                                   value="mumbai",
                                                   allow_custom_value=True,
                                                   info="Other cities are mapped automatically")
                            email = gr.Textbox(label="Email",
                                               value="anita19@yahoo.com",
                                               placeholder="customer@example.com")

                        with gr.Accordion("📄 Contract & Services", open=True):
                            contract_type = gr.Radio(
                                ["monthly", "1 year", "2 year"],
                                label="Contract Type", value="monthly")
                            internet_service = gr.Radio(
                                ["fiber optic", "dsl", "no internet service"],
                                label="Internet Service", value="fiber optic")
                            phone_service = gr.Radio(["yes", "no"],
                                                     label="Phone Service",
                                                     value="yes")
                            online_security = gr.Radio(["yes", "no"],
                                                       label="Online Security",
                                                       value="no")
                            tech_support = gr.Dropdown(
                                ["yes", "no", "no internet service"],
                                label="Tech Support", value="no")

                    # -------- right column -------- #
                    with gr.Column():
                        with gr.Accordion("💰 Billing Details", open=True):
                            tenure_months = gr.Slider(0.1, 72, value=14,
                                                      step=0.1,
                                                      label="Tenure (months)")
                            monthly_charges = gr.Slider(1, 200, value=75.5,
                                                        step=0.5,
                                                        label="Monthly Charges ($)")
                            total_charges = gr.Number(label="Total Charges ($)",
                                                      value=1100.0, minimum=0)
                            payment_method = gr.Dropdown(PAYMENTS,
                                                         label="Payment Method",
                                                         value="electronic check")

                        with gr.Accordion("📊 Engagement", open=True):
                            satisfaction_score = gr.Slider(1, 15, value=8,
                                                           step=1,
                                                           label="Satisfaction Score (1–15)")
                            support_tickets = gr.Slider(0, 99, value=2,
                                                        step=1,
                                                        label="Support Tickets Raised")
                            last_contact_date = gr.Textbox(
                                label="Last Contact Date (YYYY-MM-DD)",
                                value=str(date.today()),
                                placeholder="2026-08-25")

                predict_btn = gr.Button("🚀 Predict Churn Risk",
                                        variant="primary", size="lg")
                result_html = gr.HTML()

                inputs = [age, gender, location, email, tenure_months,
                          monthly_charges, total_charges, contract_type,
                          internet_service, phone_service, online_security,
                          tech_support, payment_method, satisfaction_score,
                          support_tickets, last_contact_date]

                predict_btn.click(fn=predict_churn, inputs=inputs,
                                  outputs=result_html)

            # ---------------- TAB 2 : DASHBOARD ---------------- #
            with gr.Tab("📊 Model Insights"):
                gr.Markdown("### How well does the model perform? "
                            "*Metrics computed live on the held-out test set.*")

                metrics_html = gr.HTML()

                with gr.Row():
                    with gr.Column():
                        donut = gr.Plot(label="Churn Split")
                    with gr.Column():
                        cm_plot = gr.Plot(label="Confusion Matrix")

                importance = gr.Plot(label="Feature Importance")

                with gr.Row():
                    dist_age = gr.Plot(label="Age Dist")
                    dist_charge = gr.Plot(label="Monthly Charges Dist")
                dist_tenure = gr.Plot(label="Tenure Dist")

        gr.HTML(FOOTER_HTML)

        # ---- events ---------------------------------------------------- #
        theme_btn.click(fn=None, inputs=None, outputs=None, js=TOGGLE_THEME_JS)
        demo.load(fn=load_dashboard, inputs=None,
                  outputs=[metrics_html, donut, cm_plot, importance,
                           dist_age, dist_charge, dist_tenure])
        demo.load(fn=None, inputs=None, outputs=None, js=FORCE_DARK_JS)

    return demo


THEME = gr.themes.Soft(
    primary_hue="fuchsia", secondary_hue="purple", neutral_hue="slate",
    font=[gr.themes.GoogleFont("Inter"), "ui-sans-serif", "system-ui"],
).set(
    button_primary_background_fill="linear-gradient(135deg, #c026d3, #9333ea)",
    button_primary_background_fill_hover="linear-gradient(135deg, #a21caf, #7e22ce)",
    block_border_width="0px",
    # dark-mode glass surfaces — applied via theme engine so radios,
    # dropdowns, numbers etc. keep their native readable styling
    block_background_fill_dark="rgba(255, 255, 255, 0.05)",
    input_background_fill_dark="rgba(255, 255, 255, 0.07)",
)


if __name__ == "__main__":
    demo = build_ui()
    demo.launch(server_name="0.0.0.0",
                server_port=int(os.getenv("PORT", 7860)),
                show_error=True,
                theme=THEME,
                css=CUSTOM_CSS)
